# Generated by Django 4.1.4 on 2023-07-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_alter_messagemodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='slug',
        ),
    ]
