# Generated by Django 4.1.4 on 2023-07-27 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_remove_messagemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
